version: "3.9"
services:
  
  todo-api:
    container_name: todo-api
    build:
      context: .
      dockerfile: Todo.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - datadog-agent
      - postgres
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DD_ENV: "demo"
      DD_SERVICE: "todo-api"
      DD_VERSION: "1.0.0"
      DD_AGENT_HOST: "datadog-agent"
      DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED: "true"
      DD_RUNTIME_METRICS_ENABLED: "true"
      
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: X@bLVUv7bKH=xy
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6739:6739"

  datadog-agent:
    container_name: datadog-agent
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_API_KEY: REPLACE_WITH_A_DATADOG_API_KEY
      DD_HOSTNAME_TRUST_UTS_NAMESPACE: "true"